/**
 * Release packaging.
 *
 *   node scripts/release.mjs              # verify + build + package
 *   node scripts/release.mjs --skip-checks  # package without running the gate
 *
 * Produces `release/she-v<version>.zip` (and `.tar.gz` on POSIX), plus a
 * `manifest.json` describing what was built and what was verified.
 *
 * Design decisions worth stating:
 *
 *  1. **The gate runs first and a failure stops the release.** A package produced
 *     from a red build is worse than no package: it looks shippable. `--skip-checks`
 *     exists for iterating on the packaging itself, and prints a loud warning.
 *
 *  2. **The artefact is a SOURCE distribution.** Shipping `node_modules` would bind
 *     the package to one platform and one Node ABI (better-sqlite3 is a native
 *     module), and every open-source install path already starts from source. The
 *     archive contains everything `./she.sh` needs to get running.
 *
 *  3. **Build output is excluded.** `dist/` is regenerated by the first launch
 *     (`scripts/she.mjs` builds when artefacts are missing), and including it would
 *     roughly double the archive for something that is rebuilt anyway.
 *
 *  4. **The manifest records the commit and whether the gate passed**, so a given
 *     archive can be traced back to a revision — and so a `--skip-checks` build is
 *     identifiable rather than indistinguishable from a verified one.
 */
import { readFileSync, writeFileSync, mkdirSync, rmSync, existsSync, readdirSync, statSync } from 'node:fs';
import { join, resolve, dirname, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '..');
const OUT_DIR = join(ROOT, 'release');

const skipChecks = process.argv.includes('--skip-checks');
const skipBuild = process.argv.includes('--skip-build');

const pkg = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8'));
const VERSION = pkg.version;
const NAME = `she-v${VERSION}`;

const step = (text) => console.log(`\n${text}`);
const ok = (text) => console.log(`  ${text}`);

/** Run a command, inheriting stdio, and return whether it succeeded. */
function run(command, args, label) {
  try {
    execFileSync(command, args, { cwd: ROOT, stdio: 'inherit', shell: process.platform === 'win32' });
    return true;
  } catch {
    console.error(`\n  [失败] ${label}`);
    return false;
  }
}

/** The current commit, or null when this is not a git checkout. */
function gitCommit() {
  try {
    return execFileSync('git', ['rev-parse', 'HEAD'], { cwd: ROOT, encoding: 'utf8' }).trim();
  } catch {
    return null;
  }
}

/** True when the working tree has uncommitted changes. */
function gitDirty() {
  try {
    const out = execFileSync('git', ['status', '--porcelain'], { cwd: ROOT, encoding: 'utf8' });
    return out.trim().length > 0;
  } catch {
    return null;
  }
}

console.log('\n============================================');
console.log(`  Pulse 发布打包  v${VERSION}`);
console.log('============================================');

/* ─── 1. The gate ─── */
if (skipChecks) {
  console.warn('\n  ⚠ 已跳过全部检查（--skip-checks）。');
  console.warn('    这个包没有经过验证，不要发布它。');
} else {
  step('[1/4] 运行完整检查（构建 + 单测 + 评测 + 全部检查脚本）');
  if (!run('pnpm', ['check:all'], '检查未通过')) {
    console.error('\n  打包已中止：检查没通过。');
    console.error('  修好之后重跑；确实要跳过用 --skip-checks（不建议）。\n');
    process.exit(1);
  }
  ok('全部通过');
}

/* ─── 2. Build ─── */
if (skipBuild) {
  step('[2/4] 跳过构建（--skip-build）');
} else {
  step('[2/4] 构建');
  if (!run('pnpm', ['-r', 'build'], '构建失败')) process.exit(1);
  ok('构建完成');
}

/* ─── 3. Assemble the archive ─── */
step('[3/4] 收集归档内容');
{
  rmSync(OUT_DIR, { recursive: true, force: true });
  mkdirSync(join(OUT_DIR, NAME), { recursive: true });
  const staging = join(OUT_DIR, NAME);

  /*
   * Top-level documentation, DISCOVERED rather than listed.
   *
   * The list used to name each file, so a new one was silently left out — which is
   * exactly what happened to `AGENTS.md`: the conventions file that documents how to work
   * in this repository was missing from the archive that ships it. Deriving the list means
   * a new doc travels with the release without anyone remembering to add it.
   */
  const topLevelDocs = readdirSync(ROOT)
    .filter((f) => (f.endsWith('.md') || f === 'LICENSE') && statSync(join(ROOT, f)).isFile());

  /** Paths included in the source distribution. */
  const INCLUDE = [
    // Everything a user needs to read before running anything.
    ...topLevelDocs,
    // Manifests and tooling.
    'package.json', 'pnpm-lock.yaml', 'pnpm-workspace.yaml', 'tsconfig.base.json',
    'config.example.yaml', '.env.example', '.gitignore', '.dockerignore', 'Dockerfile',
    // Launchers.
    'she.sh', 'SHE.bat', 'SHE-stop.bat',
    // Code and docs.
    'packages', 'scripts', 'docs', 'evals', 'plugins',
  ];

  /** Excluded even inside an included directory. */
  const EXCLUDE_DIRS = new Set([
    'node_modules', 'dist', '.she', '__tests__', '.git', 'release', 'coverage',
    '.playwright-mcp', 'test-results',
  ]);
  const EXCLUDE_FILES = /\.(log|tmp|tsbuildinfo|bak)$|^\.env$|\.module\.css\.bak$/;

  let fileCount = 0;
  let byteCount = 0;

  const copyDir = (srcDir, destDir) => {
    mkdirSync(destDir, { recursive: true });
    for (const entry of readdirSync(srcDir, { withFileTypes: true })) {
      if (EXCLUDE_DIRS.has(entry.name)) continue;
      const src = join(srcDir, entry.name);
      const dest = join(destDir, entry.name);
      if (entry.isDirectory()) { copyDir(src, dest); continue; }
      if (EXCLUDE_FILES.test(entry.name)) continue;
      if (entry.name.endsWith('.test.ts') || entry.name.endsWith('.test.tsx')) continue;
      // Copy rather than move: the working tree must stay usable.
      writeFileSync(dest, readFileSync(src));
      fileCount++;
      byteCount += statSync(src).size;
    }
  };

  for (const item of INCLUDE) {
    const src = join(ROOT, item);
    if (!existsSync(src)) continue;
    const dest = join(staging, item);
    if (statSync(src).isDirectory()) {
      copyDir(src, dest);
    } else {
      mkdirSync(dirname(dest), { recursive: true });
      writeFileSync(dest, readFileSync(src));
      fileCount++;
      byteCount += statSync(src).size;
    }
  }

  /*
   * A zip needs an archiver; `tar` is present on Windows 10+, macOS and Linux. The
   * system `tar` keeps this dependency-free, and both formats it produces are
   * readable by every platform's standard tooling.
   */
  const manifest = {
    name: NAME,
    version: VERSION,
    builtAt: new Date().toISOString(),
    node: process.version,
    platform: `${process.platform} ${process.arch}`,
    commit: gitCommit(),
    dirtyWorkingTree: gitDirty(),
    checksRan: !skipChecks,
    buildRan: !skipBuild,
    fileCount,
    unpackedBytes: byteCount,
    note: skipChecks
      ? '打包时跳过了检查，这个包没有经过验证。'
      : '打包前全部检查通过。',
  };
  writeFileSync(join(staging, 'release-manifest.json'), JSON.stringify(manifest, null, 2) + '\n', 'utf8');

  ok(`文件 ${fileCount} 个，未压缩 ${(byteCount / 1024 / 1024).toFixed(1)} MB`);
  if (manifest.commit) ok(`提交 ${manifest.commit.slice(0, 12)}${manifest.dirtyWorkingTree ? '（有未提交改动）' : ''}`);
}

/* ─── 4. Compress ─── */
step('[4/4] 压缩');
{
  const staging = join(OUT_DIR, NAME);
  const produced = [];

  // `tar` handles both; zip is friendlier for a Windows user, tar.gz for POSIX.
  const formats = process.platform === 'win32'
    ? [['zip', ['-a', '-c', '-f']], ['tar.gz', ['-czf']]]
    : [['tar.gz', ['-czf']], ['zip', ['-r', '-q']]];

  for (const [ext, flags] of formats) {
    const out = join(OUT_DIR, `${NAME}.${ext}`);
    try {
      if (ext === 'zip') {
        // `-a` lets bsdtar pick the format from the extension; -q keeps it quiet.
        execFileSync('tar', [...flags, out, '-C', OUT_DIR, NAME], { stdio: 'pipe' });
      } else {
        execFileSync('tar', [...flags, out, '-C', OUT_DIR, NAME], { stdio: 'pipe' });
      }
      const size = statSync(out).size;
      produced.push({ file: relative(ROOT, out).replace(/\\/g, '/'), bytes: size });
      ok(`${relative(ROOT, out).replace(/\\/g, '/')}  ${(size / 1024 / 1024).toFixed(1)} MB`);
    } catch (err) {
      ok(`跳过 ${ext}: ${(err instanceof Error ? err.message : String(err)).slice(0, 80)}`);
    }
  }

  // The staging tree is only needed until the archives exist.
  rmSync(staging, { recursive: true, force: true });

  if (produced.length === 0) {
    console.error('\n  没有生成任何归档（tar 不可用？）');
    process.exit(1);
  }

  writeFileSync(join(OUT_DIR, 'manifest.json'), JSON.stringify({ ...readJson(join(OUT_DIR, 'manifest.json')), artifacts: produced }, null, 2) + '\n', 'utf8');
}

function readJson(path) {
  try { return JSON.parse(readFileSync(path, 'utf8')); } catch { return {}; }
}

console.log('\n============================================');
console.log(`  完成：release/${NAME}.*`);
console.log('  安装：解压后运行  ./she.sh    （Windows: SHE.bat）');
if (skipChecks) console.log('  ⚠ 未经检查的包 —— 仅供本地尝试，不要发布。');
console.log('============================================\n');
